sudo: false
language: elixir
git:
  quiet: true
  depth: 3
elixir:
  - 1.13
otp_release:
  - 22.0
matrix:
  exclude:
    - elixir: 1.6
      otp_release: 22.0
env:
  - MIX_ENV=test VERBOSE_TESTS=true
cache:
  directories:
    - _build
    - deps
before_script:
  - epmd -daemon
  - mix do deps.get
script:
  - bin/travis
notifications:
  email:
    - paulschoenfelder@gmail.com
